// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Stadium.EFCore;
using Web_Stadium.EFCore;

#nullable disable

namespace Web_Stadium.Migrations
{
    [DbContext(typeof(SanBongContext))]
    [Migration("20260410092038_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_Stadium.EFCore.DanhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SanBongId")
                        .HasColumnType("int");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SanBongId");

                    b.HasIndex("UserId");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.DatSan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhungGioId")
                        .HasColumnType("int");

                    b.Property<string>("MaXacNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThiDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhungGioId");

                    b.HasIndex("UserId");

                    b.ToTable("DatSans");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.DatSan_DichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatSanId")
                        .HasColumnType("int");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatSanId");

                    b.HasIndex("DichVuId");

                    b.ToTable("DatSan_DichVus");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.DichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.KhungGio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaGioVang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int>("SanBongId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianHetGiuCho")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SanBongId");

                    b.ToTable("KhungGios");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.Matchmaking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatSanId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNguoiCanThem")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatSanId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Matchmakings");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.SanBong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DanhGiaTrungBinh")
                        .HasColumnType("float");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LoaiCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiSan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Quan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("SanBongs");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.DanhGia", b =>
                {
                    b.HasOne("Web_Stadium.EFCore.SanBong", "SanBong")
                        .WithMany("DanhGias")
                        .HasForeignKey("SanBongId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Web_Stadium.EFCore.User", "User")
                        .WithMany("DanhGias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SanBong");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.DatSan", b =>
                {
                    b.HasOne("Web_Stadium.EFCore.KhungGio", "KhungGio")
                        .WithMany("DanhSachDatSan")
                        .HasForeignKey("KhungGioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Web_Stadium.EFCore.User", "User")
                        .WithMany("DanhSachDatSan")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhungGio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.DatSan_DichVu", b =>
                {
                    b.HasOne("Web_Stadium.EFCore.DatSan", "DatSan")
                        .WithMany("DichVuKemTheo")
                        .HasForeignKey("DatSanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Web_Stadium.EFCore.DichVu", "DichVu")
                        .WithMany("DatSan_DichVus")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DatSan");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.KhungGio", b =>
                {
                    b.HasOne("Web_Stadium.EFCore.SanBong", "SanBong")
                        .WithMany("KhungGios")
                        .HasForeignKey("SanBongId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SanBong");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.Matchmaking", b =>
                {
                    b.HasOne("Web_Stadium.EFCore.DatSan", "DatSan")
                        .WithOne("matchmaking")
                        .HasForeignKey("Web_Stadium.EFCore.Matchmaking", "DatSanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Web_Stadium.EFCore.User", "User")
                        .WithMany("Matchmakings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DatSan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.SanBong", b =>
                {
                    b.HasOne("Web_Stadium.EFCore.User", "Owner")
                        .WithMany("SanBongSoHuu")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.DatSan", b =>
                {
                    b.Navigation("DichVuKemTheo");

                    b.Navigation("matchmaking");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.DichVu", b =>
                {
                    b.Navigation("DatSan_DichVus");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.KhungGio", b =>
                {
                    b.Navigation("DanhSachDatSan");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.SanBong", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("KhungGios");
                });

            modelBuilder.Entity("Web_Stadium.EFCore.User", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DanhSachDatSan");

                    b.Navigation("Matchmakings");

                    b.Navigation("SanBongSoHuu");
                });
#pragma warning restore 612, 618
        }
    }
}
